### ISSUE TITLE
bill of materials

### ISSUE THREAD

**Issue by BMaxV** [FireMarshmellow/M.I.M.O.S.A#13]
Hey, cool project!

Can you add a list with the hardware you used?

You do mention them in the video, but it would be more handy with links.

**Comment by Callsign-Carrot** [comment]
Any RGB strip and a microcontroller that is supported by WLED will work.
I snagged [this strip](https://www.amazon.com/dp/B0BHLFBTP7?ref=ppx_yo2ov_dt_b_product_details&th=1) and [this controller](https://www.amazon.com/dp/B09SPYY61L?ref=ppx_yo2ov_dt_b_product_details&th=1). Again, these are just what I grabbed. Virtually all RGB strips work with WLED so if you find a better deal and in a better count, take it. ESP8266 and ESP32 are the best supported controllers for WLED.

**Comment by FireMarshmellow** [comment]
https://kno.wled.ge/basics/compatible-hardware/
