### ISSUE TITLE
TemplateNotFound

### ISSUE THREAD

**Issue by mojamuto** [FireMarshmellow/M.I.M.O.S.A#16]
Hello, I cloned the repository, do pip install -r requirements edit ip_list and start app.pyand when I open the address in the browser I get this error:

` * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.140:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 102-059-950
127.0.0.1 - - [18/Apr/2023 16:26:39] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/Git/github/M.I.M.O.S.A/app.py", line 35, in index
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlos/.local/lib/python3.11/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
127.0.0.1 - - [18/Apr/2023 16:26:39] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [18/Apr/2023 16:26:39] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [18/Apr/2023 16:26:39] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
`

![fallo](https://user-images.githubusercontent.com/36079583/232808454-6b63889a-ba28-49fb-b203-f81ded37af16.png)

I don't know what I'm doing wrong, I'm on void linux

**Comment by FireMarshmellow** [comment]
@mojamuto  Have you changed any directories?

**Comment by mojamuto** [comment]
I have not changed anything, my steps are:
1. git clone https://github.com/FireMarshmellow/M.I.M.O.S.A.git
2. cd M.I.M.O.S.A
3. Edit the ip_list variable in wled_api.py
4. python app.py

I can make a video or send you any file/info you need

**Comment by FireMarshmellow** [comment]
@mojamuto 
That's alright I believe you, I'm gonna spin up a VM to see if I can get the same issue.

**Comment by mojamuto** [comment]
thank you very much and sorry for giving you work

**Comment by FireMarshmellow** [comment]
@mojamuto why can't you be like the other kids and use ubuntu server XD
it doesn't even want to install flask for me

**Comment by mojamuto** [comment]
hahahaha no problem I will investigate if I find any solution, reading flask says that adding app=Flask(__name__,template_folder='Templates')
It should solve the problem, I just tried it and it no longer gives me the error, but I only have this:
![fallo](https://user-images.githubusercontent.com/36079583/232878928-110817ab-c4d1-42da-970a-cb3fed5f8ed1.png)

**Comment by mojamuto** [comment]
I have found the error, which cannot be explained because it only happens to me.
You have to rename the Templates folder and use only lower case, and then the failure that the page does not load well, is renaming the Static folder and use only lower case.
![fallo](https://user-images.githubusercontent.com/36079583/232916910-e8f0d393-27ab-444a-8f1b-e329d036a0ae.png)

Static => static
Templates => templates

thanks  @FireMarshmellow  for the support

**Comment by FireMarshmellow** [comment]
@mojamuto I guess good to know void linux capsLock sensitive 😂😂
I'll make sure to change it in the next update if it screw up anything on my machine

**Comment by mojamuto** [comment]
I'm sorry to write in a closed thread, but I don't want to open another one, I've been testing M.I.M.O.S.A in raspbian (Raspberry pi), Arch and ubuntu server, and I have the same problem in all of them, I wanted to clarify that it's not just void linux, it's in linux in general and possibly for the same in macos, but I can't be sure.
I tried other systems because when I saw your youtube video for the second time I realized that you are in windows, I was calm in knowing why it happened "only to me" :joy::joy:

thanks again

**Comment by FireMarshmellow** [comment]
@mojamuto Thanks for investigating the problem, I've pushed the fix to main. I called it "added support for caps lock sensitive Linux" 😂😂
