### ISSUE TITLE
How to start 

### ISSUE THREAD

**Issue by huizebruin** [FireMarshmellow/M.I.M.O.S.A#20]
Where must start.
What do I need to have to install it on it.

Need i a Linux of Windows Setup.

And does it also works without the wled.
I don't have that at this moment but want to start with this project.
I have 4 of those whit a lot of components.

**Comment by FireMarshmellow** [comment]
To start with you don't need the Wleds you can add them in later.
It can run on windows or Linux, just follow the instructions in the readme file.

**Comment by huizebruin** [comment]
But what software do I need to start. 

I'm using windows, must I install python on it and place the GitHub information in it and then execute the Install link?

**Comment by FireMarshmellow** [comment]
@huizebruin to make it easier for you I added a executable version of the app, however it will not let you add LED light strips so you can use it to build up your library for now. You might have to install Python from the Microsoft app store.

**Comment by huizebruin** [comment]
thanks

**Comment by huizebruin** [comment]
its working, thanks

**Comment by huizebruin** [comment]
can i update to 2.1 by copy the data from the GitHub to the folder without the database.

**Comment by FireMarshmellow** [comment]
You should be able to, but I did have to add an extra row in the database which might cause issues. But on this version, you can actually at the lights without having to go in the code.
Duplicate your database, and if it doesn't work, we'll figure something out.

**Comment by huizebruin** [comment]
I will try it, out and will inform you about it.

**Comment by huizebruin** [comment]
I downloaded a SQL Editor for windows and put a extra row in the database with the name ip  and tekst row. And that's it, and then started the new 2.1 version exe.

And it worked. (I made a backup before this)

**Comment by FireMarshmellow** [comment]
Awesome! When you set up with W LED, you should just have to edit position and IP. I would probably do that through the SQL editor otherwise you're going to be doing each item individual.
