### ISSUE TITLE
Can't locate a newly created item without refreshing the page.

### ISSUE THREAD

**Issue by Callsign-Carrot** [FireMarshmellow/M.I.M.O.S.A#22]
A quick and dirty fix is adding `loadItems();` and `location.reload();` at the end of the addItem function in script.js. I am looking into a better solution but I just started learning flask and sqlite.
Edit: I noticed just calling loadItems() twice resolves the issue but displays all items twice and only the second iteration of the new item works.

**Comment by FireMarshmellow** [comment]
@Callsign-Carrot that's interesting mine pop up immediately, are you using mimosa v2.0?

**Comment by Callsign-Carrot** [comment]
I mean when hitting the locate button. I keep getting a 404. I actually redownloaded everything when you merged for 2.0. 
![image](https://user-images.githubusercontent.com/107817828/233206230-322e7007-98f5-4cc9-adbb-e3c8cf13a161.png)

**Comment by FireMarshmellow** [comment]
Did you add the Wled IP addresses to the Python list?

**Comment by Callsign-Carrot** [comment]
Yes, everything works except hitting locate on the newest item. if I refresh the page the newest item works, but before then the locate button will not.

**Comment by FireMarshmellow** [comment]
Now I get the issue

**Comment by FireMarshmellow** [comment]
Great news we have a fix for this bug, it will be released later today.
