### ISSUE TITLE
Duration of LED stays on after Locate

### ISSUE THREAD

**Issue by MrPresident2** [FireMarshmellow/M.I.M.O.S.A#26]
Hey, Is there a way to change the duration of the LEDs staying on after you press locate? 
or where can I find it in the code and change it?
its just turn off to fast for me to find the location which make it unusable ( FOR ME) thanks :D :D

**Comment by MrPresident2** [comment]
Nevermind found it under wled_api

**Comment by FireMarshmellow** [comment]
@MrPresident2  I'm glad you figured it out, I'm planning to add it to the GUI but it's not priority.

**Comment by MrPresident2** [comment]
I have a question but I do not want to open another thread for it, Is there a way to add a command to toggle the Wled leds?
I don't want the LEDs to work all the time, but adding one of the macro commands to turn them on, locate, then toggle them off could be a great feature to add. what do you think? is there a way for me to add this to the code? or maybe it's something you will want to add?

Btw is there a discord server or something I can't join to chat with you? I might have a great idea for you ;)

**Comment by MrPresident2** [comment]
> @MrPresident2 I'm glad you figured it out, I'm planning to add it to the GUI but it's not priority.

I have a question but I do not want to open another thread for it, Is there a way to add a command to toggle the Wled leds?
I don't want the LEDs to work all the time, but adding one of the macro commands to turn them on, locate, then toggle them off could be a great feature to add. what do you think? is there a way for me to add this to the code? or maybe it's something you will want to add?

Btw is there a discord server or something I can't join to chat with you? I might have a great idea for you ;)

**Comment by FireMarshmellow** [comment]
@MrPresident2 yeah I do have a server it's not very developed but here it is https://discord.gg/xw4t3kD4 
Also I can write you some custom code to do that before I find a way of implementing it into the interface, but I'll have to do it tomorrow.
