### ISSUE TITLE
Issues updating existing items

### ISSUE THREAD

**Issue by straysolutions** [FireMarshmellow/M.I.M.O.S.A#27]
Just tried the new v2 version. Love the changes! Only issue I have found so far is updating existing items (I have most of what you include as examples lol). When I try to update them the value doesn't change and the app window is listing out this error:

Error on request:
Traceback (most recent call last):
  File "werkzeug\debug\__init__.py", line 329, in debug_application
  File "flask\app.py", line 2551, in __call__
  File "flask\app.py", line 2531, in wsgi_app
  File "flask\app.py", line 2528, in wsgi_app
  File "flask\app.py", line 1825, in full_dispatch_request
  File "flask\app.py", line 1823, in full_dispatch_request
  File "flask\app.py", line 1799, in dispatch_request
  File "app.py", line 88, in item
sqlite3.ProgrammingError: Cannot operate on a closed database.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "werkzeug\serving.py", line 333, in run_wsgi
  File "werkzeug\serving.py", line 322, in execute
  File "werkzeug\debug\__init__.py", line 344, in debug_application
  File "werkzeug\debug\tbtools.py", line 331, in render_debugger_html
  File "werkzeug\debug\tbtools.py", line 291, in render_traceback_html
  File "werkzeug\debug\tbtools.py", line 413, in render_html
IndexError: list index out of range

Really appreciate you opening this up as I have built two of these for myself this week! (so MANY solder points!)

**Comment by straysolutions** [comment]
oh forgot to add the value I am trying to update is the wled IP. It's reachable and the json page loads with no issue.

**Comment by FireMarshmellow** [comment]
I'm having trouble recreating this error, are you using the precompiled .exe version or the Python script? I'm also assuming you're using the latest build 2.1?

**Comment by straysolutions** [comment]
Yep, I am using the latest build and I have tried both the exe (ran as admin as well) and also just launching the app.py

Interestingly there is no error when launched through app.py but the wled field still fails to update. Here I loaded the site. Edited the wled field and refreshed:

 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.0.32:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 482-326-028
10.0.0.32 - - [22/Apr/2023 10:02:45] "GET / HTTP/1.1" 200 -
10.0.0.32 - - [22/Apr/2023 10:02:45] "GET /static/script.js HTTP/1.1" 304 -
10.0.0.32 - - [22/Apr/2023 10:02:45] "GET /api/items HTTP/1.1" 200 -
10.0.0.32 - - [22/Apr/2023 10:03:01] "PUT /api/items/1 HTTP/1.1" 200 -
10.0.0.32 - - [22/Apr/2023 10:03:04] "GET / HTTP/1.1" 200 -
10.0.0.32 - - [22/Apr/2023 10:03:04] "GET /static/script.js HTTP/1.1" 304 -
10.0.0.32 - - [22/Apr/2023 10:03:04] "GET /api/items HTTP/1.1" 200 -

**Comment by straysolutions** [comment]
also I am able to update other fields without issue and add items as well. It only seems to be impacting editing that wled field. If I attempt to edit the wled field on a new item I've added it still sends the signal to the previous ip/position. I tested to see if I can update position and that works fine so everything seems to be pointing towards the code that updates the wled field. I barely know what I am doing with python but when looking over the database script it looks like the update portion doesn't include IP? I see it in the write item portion but not there so figured I would ask: 

def update_item(id, data):
    conn = get_db()
    conn.execute('UPDATE items SET name = ?, link = ?, image = ?, position = ?, quantity = ? WHERE id = ?', [data['name'], data['link'], data['image'], data['position'], data['quantity'], id])
    conn.commit()
    conn.close()

**Comment by FireMarshmellow** [comment]
@straysolutions no that's spot on you found it I was just about to write a comment saying I figured it out, I forgot to add IP as a field to update. I'll push an update in a minute.

**Comment by FireMarshmellow** [comment]
@straysolutions I pushed the fix,  let me know if that solved the issue.

**Comment by straysolutions** [comment]
AWESOME! Tested editing ip address to both bins I had built and changed positions. All working as expected. Thanks for the quick resolution!
