### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by Steinherkules** [FireMarshmellow/M.I.M.O.S.A#28]
Hello the script.js file is not working for me. 
![fehler](https://user-images.githubusercontent.com/131468760/233789242-018326a0-e9ab-42e7-a6e4-eacd52f79209.PNG)

**Comment by FireMarshmellow** [comment]
can you give me any more info? did you change anything after cloning the repository?

**Comment by Steinherkules** [comment]
no i didn't  change anything after the repo. i did everything in the readme.txt. and when i try to open the script .js i get this message. (kompilierungsfehler=compile error)
![fehler2](https://user-images.githubusercontent.com/131468760/233792904-0592673c-f7d2-4bd5-a684-0e8531eac2f9.PNG)

**Comment by Callsign-Carrot** [comment]
You do not run that script. That script is used by the website. To start it up you run app.py or the exe. You do not have to touch anything else.

**Comment by Steinherkules** [comment]
i deleted everything and started from begining but it still doesn't work.

**Comment by Callsign-Carrot** [comment]
Do not run anything. Only start the exe file or app.py.

**Comment by FireMarshmellow** [comment]
I'm gonna assume this issue has been resolved
