### ISSUE TITLE
Multiple LED per item

### ISSUE THREAD

**Issue by trondage** [FireMarshmellow/M.I.M.O.S.A#33]
I would like to add multiple LEDs per item in location, since I have used a strip to minimize soldering.
If I'm correct WLED doesn't support more that ~30 segments, so a way of adding multiple in MIMOSA could have solved that.

**Comment by FireMarshmellow** [comment]
This is a feature that I want to add, but we are currently running into some annoying limitations with WLED API. And keeping it simple to deploy.

**Comment by bmiki75** [comment]
to achive this i think it is possible to change from :
def send_request(target_ip, start_num, stop_num, color):
    url = f"http://{target_ip}/json/state" # construct URL using the target IP address
    state = {"seg": [{"id": 0, "start": start_num, "stop": stop_num, "col": [color]}]}
    response = requests.post(url, json=state)
to:
def send_request(target_ip, start_num, stop_num, color,nled_item):
    url = f"http://{target_ip}/json/state" # construct URL using the target IP address
    state = {"seg": [{"id": 0, "start": start_num *nled_item , "stop": (start_num*nled_item ) + nled_item, "col": [color]}]}
    response = requests.post(url, json=state)
or change approach with:
i=0
n_led_item=5
Color="FF0000"
scolor=""
start_num=10
while i < n_led_item:
  scolor+=str(start_num + i) + ",\"" + Color + "\","
  i += 1
state = "{\"seg\":{\"i\"[" + scolor[0:-1] + "]}}"
