### ISSUE TITLE
Framework for the frontend

### ISSUE THREAD

**Issue by tpickett** [FireMarshmellow/M.I.M.O.S.A#50]
Is there any reason that Mimosa is sticking to raw Javascript for updating the DOM? 
I think this project could benefit from using some sort of frontend framework for generating the HTML/CSS/JS. just for the speed of development and decoupling of JS modules. 
I myself am partial to Vue and have recreated the whole frontend in vue 3 with the features mentioned in #49 and wondered if anyone else could benefit from my work putting mimosa into framework.

Let me know if  you'd like to see Mimosa implemented in Vue.js?

**Comment by FireMarshmellow** [comment]
Probably because I don't know what that is, we are finishing up an update Should be out soon.

https://github.com/JustReit/M.I.M.O.S.A

**Comment by tpickett** [comment]
well if you want to see it working in [Vue](https://vuejs.org/) I have a working docker image up @ [tpickett/mimosa](https://hub.docker.com/layers/tpickett/mimosa/v2/images/sha256-ca10da5ce3763c9f15931292113e5ba5e8c65b6d85f06f2fa95c6b0f1174a370?context=repo) I had to make some changes to the db to allow joins so the queries don't get so hairy - but i updated the data.db file to represent the changes in the docker image. worth a look if you have the time ;)

install docker desktop by visiting https://www.docker.com/products/docker-desktop/
once installed - then run 
```docker run --rm -it --name mimosa -p 5000:5000 tpickett/mimosa:v2```
then visit http://localhost:5000 to see the new Vue interface. 

![MIMOSA-v2-update-part](https://github.com/FireMarshmellow/M.I.M.O.S.A/assets/2249555/4351eae7-c685-4fda-97ef-d73562f7b7c5)
![MIMOSA-v2-single organizer](https://github.com/FireMarshmellow/M.I.M.O.S.A/assets/2249555/9d19342a-ba7c-41bd-9035-466ea0fe0732)
![MIMOSA-v2-organizer-list](https://github.com/FireMarshmellow/M.I.M.O.S.A/assets/2249555/3bc890e4-5bc4-4558-ab01-b37cd5adf5f8)

**Comment by tpickett** [comment]
i understand if your still not interested - ill just keep it for myself ;) you can close this whenever.

**Comment by FireMarshmellow** [comment]
Can't say I like the look of it,but too old home assistent.

**Comment by tpickett** [comment]
alright. ill keep it in my fork then. will be awaiting that new update!

**Comment by FireMarshmellow** [comment]
Version 3 came out earlier today, would you still be interested in helping me set up get up actions for docker?
